# .github/workflows/aws-sam-deploy.yml

name: Deploy Backend and Frontend to AWS 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install
        
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: Upload frontend to S3
        run: aws s3 sync frontend/dist/ s3://club-explorer-frontend --delete --acl public-read

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build project
        run: sam build

      - name: Deploy to AWS
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name football-explorer-app --capabilities CAPABILITY_IAM --region eu-north-1
