# .github/workflows/aws-sam-deploy.yml

name: Deploy to AWS via SAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build project
        run: sam build

      - name: Deploy to AWS
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name football-explorer-app --capabilities CAPABILITY_IAM
